### ISSUE TITLE
Defect #2 Ошибка 

### ISSUE THREAD

**Issue by beznigaeva** [mrmiv/tusur.refectory#2]
### Пробный дефект № 2 

- используя новые **лейблы** 

1. добавляя _изображения_ 

- [ ] меняя форматирование

@mrmiv   #1 

> 1 2 3
![photo-1499244571948-7ccddb3583f1](https://user-images.githubusercontent.com/56103256/66100234-5269be80-e5d4-11e9-970d-47481db401f7.jpg)

**Comment by mrmiv** [comment]
Ошибка повторяется в Х барузере
