### ISSUE TITLE
Defect#5 Некорректное расположение иконок

### ISSUE THREAD

**Issue by PoberezhetsElizaveta** [mrmiv/tusur.refectory#8]
**Описание:** Близкое расположение иконки к названию вкладки

**Шаги воспроизведения:** 
1. Переход по ветке "Main".
2. В шапке нажать страницу "Menu"/ "Shop".
_Ожидаемый результат:_
 menu/shop иконки располагаются на расстоянии пробела.
_Действительный результат:_ 
 menu/shop слишком близкое расположение иконок к названию вкладок.

**Примечание:**
Версия Commit-разработка шапки (v1.0)

![Некорректное расположение иконок](https://user-images.githubusercontent.com/56376375/67451224-0d243400-f64a-11e9-8c58-2873772c0bfc.gif)

**Comment by AnastasiaIsakova** [comment]
Исправлено
