### ISSUE TITLE
Defect#6 Некорректное расположение иконок

### ISSUE THREAD

**Issue by NikitinaKatya** [mrmiv/tusur.refectory#9]
**Описание:** Расположение иконки и название вкладки по правой стороне

**Шаги воспроизведения:**
1. Переход по ветке "Main".
2. Нажатие на всплывающее меню. 
_Ожидаемый результат:_
Название и иконки располагаются по правой стороне.
_Действительный результат:_
Название и иконки располагаются по левой стороне.
Примечание:
Версия Commit-разработка шапки (v1.0)
 
![11](https://user-images.githubusercontent.com/56376602/67471481-ae76ae80-f679-11e9-9b50-aa3c12830be2.PNG)

**Comment by AnastasiaIsakova** [comment]
я случайно))
